# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Uses example

on:
 workflow_dispatch:

jobs:
  Uses-example:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code with an action
      uses: actions/checkout@v4
    - name: Use python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - name: Run script
      run: python my_script.py
